name: Docker build -> push -> deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build Jar
      run: ./mvnw clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:4.2 .

    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:4.2


        - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{secrets.EC2_USER}}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop spring-demo || true
          docker rm spring-demo || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:4.2
          docker run -d -p 5058:5058 --name spring-demo \
            ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:4.2
